services:
    caddy:
        image: caddy:2
        container_name: caddy
        restart: unless-stopped
        networks:
            - caddys
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ../data/caddy/data:/data
            - ../data/caddy/config:/config
            - ../data/caddy/log:/var/log/caddy
            - ./conf:/etc/caddy
            - ../strawmelonjuice-site/out:/srv/strawmelonjuice-site/

networks:
    caddys:
        name: caddys
        driver: bridge
