database:
    name: psycopg2
    args:
        user: synapse
        password: synapsepassword
        database: synapse
        host: db
        cp_min: 5
        cp_max: 10
enable_registration: false
enable_registration_without_verification: false
caches:
    global_factor: 2.0
retention:
    enabled: true
    purge_jobs:
        - longest_max_lifetime: 30d
          interval: 1d
app_service_config_files:
    - /data/signal-registration.yaml
    - /data/whatsapp-registration.yaml
