services:
  strawmedia:
    image: strawmelonjuice/strawmediajuice:1.2.1
    restart: unless-stopped
    environment:
      - PORT=3022
    ports:
      - "3022:3022"
    volumes:
      - ./data/:/app/data/
