services:
    strawmedia:
        image: strawmelonjuice/strawmediajuice:1.2.1
        restart: unless-stopped
        environment:
            - PORT=3022
        networks:
            - caddys
        volumes:
            - ../data/strawmediajuice:/app/data/
networks:
    caddys:
        external: true
